"""Add doctor and patient profile enhancements

Revision ID: 1f038b941edf
Revises: a1b2c3d4e5f6
Create Date: 2025-12-31 04:38:22.504445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f038b941edf'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('title', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('nid_number', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('qualifications', sa.Text(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('sub_specializations', sa.JSON(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('services', sa.JSON(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('work_experience', sa.JSON(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('hospital_address', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('hospital_city', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('hospital_country', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('chamber_name', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('chamber_address', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('chamber_city', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('follow_up_fee', sa.Float(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('visiting_hours', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('appointment_duration', sa.Integer(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('languages_spoken', sa.JSON(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('telemedicine_available', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('doctor_profiles', sa.Column('telemedicine_platforms', sa.JSON(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patient_profiles', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('nid_number', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('address', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('district', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('has_diabetes', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_hypertension', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_heart_disease', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_asthma', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_kidney_disease', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_liver_disease', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_thyroid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_neurological', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('chronic_conditions_notes', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('drug_allergies', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('food_allergies', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('environmental_allergies', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('surgeries', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('treatment_description', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('hospitalizations', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('family_has_diabetes', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_has_hypertension', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_has_heart_disease', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_has_cancer', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_has_stroke', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_has_asthma', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_has_thalassemia', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_has_blood_disorders', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('family_history_notes', sa.Text(), nullable=True))
    op.add_column('patient_profiles', sa.Column('smoking_details', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('alcohol_details', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('tobacco_use', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('drug_use', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('exercise_type', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('exercise_frequency', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('sleep_quality', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('diet_restrictions', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('water_intake', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('stress_level', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('mental_health_history', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('vaccination_status', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('vaccinations', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('has_epi_vaccination', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_covid_vaccination', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('covid_vaccine_doses', sa.Integer(), nullable=True))
    op.add_column('patient_profiles', sa.Column('has_hepatitis_vaccination', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_tb_vaccination', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('has_tt_vaccination', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('preferred_language', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_address', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('consent_research', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('patient_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('patient_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('patient_profiles', 'has_cancer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_arthritis',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_stroke',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_epilepsy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_mental_health',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'surgery_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('patient_profiles', 'family_has_mental_health',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'family_has_kidney_disease',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'family_has_thyroid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'currently_in_therapy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_profiles', 'currently_in_therapy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'family_has_thyroid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'family_has_kidney_disease',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'family_has_mental_health',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'surgery_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('patient_profiles', 'has_mental_health',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_epilepsy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_stroke',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_arthritis',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patient_profiles', 'has_cancer',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('patient_profiles', 'updated_at')
    op.drop_column('patient_profiles', 'created_at')
    op.drop_column('patient_profiles', 'consent_research')
    op.drop_column('patient_profiles', 'emergency_address')
    op.drop_column('patient_profiles', 'notification_preferences')
    op.drop_column('patient_profiles', 'preferred_language')
    op.drop_column('patient_profiles', 'has_tt_vaccination')
    op.drop_column('patient_profiles', 'has_tb_vaccination')
    op.drop_column('patient_profiles', 'has_hepatitis_vaccination')
    op.drop_column('patient_profiles', 'covid_vaccine_doses')
    op.drop_column('patient_profiles', 'has_covid_vaccination')
    op.drop_column('patient_profiles', 'has_epi_vaccination')
    op.drop_column('patient_profiles', 'vaccinations')
    op.drop_column('patient_profiles', 'vaccination_status')
    op.drop_column('patient_profiles', 'mental_health_history')
    op.drop_column('patient_profiles', 'stress_level')
    op.drop_column('patient_profiles', 'water_intake')
    op.drop_column('patient_profiles', 'diet_restrictions')
    op.drop_column('patient_profiles', 'sleep_quality')
    op.drop_column('patient_profiles', 'exercise_frequency')
    op.drop_column('patient_profiles', 'exercise_type')
    op.drop_column('patient_profiles', 'drug_use')
    op.drop_column('patient_profiles', 'tobacco_use')
    op.drop_column('patient_profiles', 'alcohol_details')
    op.drop_column('patient_profiles', 'smoking_details')
    op.drop_column('patient_profiles', 'family_history_notes')
    op.drop_column('patient_profiles', 'family_has_blood_disorders')
    op.drop_column('patient_profiles', 'family_has_thalassemia')
    op.drop_column('patient_profiles', 'family_has_asthma')
    op.drop_column('patient_profiles', 'family_has_stroke')
    op.drop_column('patient_profiles', 'family_has_cancer')
    op.drop_column('patient_profiles', 'family_has_heart_disease')
    op.drop_column('patient_profiles', 'family_has_hypertension')
    op.drop_column('patient_profiles', 'family_has_diabetes')
    op.drop_column('patient_profiles', 'hospitalizations')
    op.drop_column('patient_profiles', 'treatment_description')
    op.drop_column('patient_profiles', 'surgeries')
    op.drop_column('patient_profiles', 'environmental_allergies')
    op.drop_column('patient_profiles', 'food_allergies')
    op.drop_column('patient_profiles', 'drug_allergies')
    op.drop_column('patient_profiles', 'chronic_conditions_notes')
    op.drop_column('patient_profiles', 'has_neurological')
    op.drop_column('patient_profiles', 'has_thyroid')
    op.drop_column('patient_profiles', 'has_liver_disease')
    op.drop_column('patient_profiles', 'has_kidney_disease')
    op.drop_column('patient_profiles', 'has_asthma')
    op.drop_column('patient_profiles', 'has_heart_disease')
    op.drop_column('patient_profiles', 'has_hypertension')
    op.drop_column('patient_profiles', 'has_diabetes')
    op.drop_column('patient_profiles', 'marital_status')
    op.drop_column('patient_profiles', 'postal_code')
    op.drop_column('patient_profiles', 'district')
    op.drop_column('patient_profiles', 'address')
    op.drop_column('patient_profiles', 'nid_number')
    op.drop_column('patient_profiles', 'profile_photo_url')
    op.drop_column('doctor_profiles', 'updated_at')
    op.drop_column('doctor_profiles', 'telemedicine_platforms')
    op.drop_column('doctor_profiles', 'telemedicine_available')
    op.drop_column('doctor_profiles', 'languages_spoken')
    op.drop_column('doctor_profiles', 'about')
    op.drop_column('doctor_profiles', 'emergency_contact')
    op.drop_column('doctor_profiles', 'appointment_duration')
    op.drop_column('doctor_profiles', 'visiting_hours')
    op.drop_column('doctor_profiles', 'follow_up_fee')
    op.drop_column('doctor_profiles', 'chamber_city')
    op.drop_column('doctor_profiles', 'chamber_address')
    op.drop_column('doctor_profiles', 'chamber_name')
    op.drop_column('doctor_profiles', 'hospital_country')
    op.drop_column('doctor_profiles', 'hospital_city')
    op.drop_column('doctor_profiles', 'hospital_address')
    op.drop_column('doctor_profiles', 'work_experience')
    op.drop_column('doctor_profiles', 'services')
    op.drop_column('doctor_profiles', 'sub_specializations')
    op.drop_column('doctor_profiles', 'education')
    op.drop_column('doctor_profiles', 'qualifications')
    op.drop_column('doctor_profiles', 'nid_number')
    op.drop_column('doctor_profiles', 'date_of_birth')
    op.drop_column('doctor_profiles', 'gender')
    op.drop_column('doctor_profiles', 'title')
    # ### end Alembic commands ###
