"""add onboarding_completed to profiles

Revision ID: 3a2e34081573
Revises: f5419eaa3cf6
Create Date: 2025-12-22 07:19:37.467484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2e34081573'
down_revision: Union[str, Sequence[str], None] = 'f5419eaa3cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'onboarding_completed')
    # ### end Alembic commands ###
