"""add_lat_lng_to_doctor_profiles

Revision ID: 51ce17656b64
Revises: 54207bbc5c73
Create Date: 2026-01-13 10:29:40.195948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ce17656b64'
down_revision: Union[str, Sequence[str], None] = '54207bbc5c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_profiles', 'longitude')
    op.drop_column('doctor_profiles', 'latitude')
    # ### end Alembic commands ###
