"""Add hospital and chamber coordinates to doctor profiles

Revision ID: af3b8aa23f44
Revises: c2fee4c5a250
Create Date: 2026-01-14 03:29:54.006856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3b8aa23f44'
down_revision: Union[str, Sequence[str], None] = 'c2fee4c5a250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('hospital_latitude', sa.Float(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('hospital_longitude', sa.Float(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('chamber_latitude', sa.Float(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('chamber_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_profiles', 'chamber_longitude')
    op.drop_column('doctor_profiles', 'chamber_latitude')
    op.drop_column('doctor_profiles', 'hospital_longitude')
    op.drop_column('doctor_profiles', 'hospital_latitude')
    # ### end Alembic commands ###
