"""Add specialities table and speciality_id to doctor_profiles

Revision ID: bffcf6a630a1
Revises: 1f038b941edf
Create Date: 2026-01-06 01:46:42.793274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffcf6a630a1'
down_revision: Union[str, Sequence[str], None] = '1f038b941edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('doctor_profiles', sa.Column('speciality_id', sa.Integer(), nullable=True))
    op.alter_column('doctor_profiles', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'doctor_profiles', 'specialities', ['speciality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_profiles', type_='foreignkey')
    op.alter_column('doctor_profiles', 'specialization',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('doctor_profiles', 'speciality_id')
    op.drop_table('specialities')
    # ### end Alembic commands ###
