"""update_onboarding_models

Revision ID: d9f8a08dcfb3
Revises: 3a2e34081573
Create Date: 2025-12-22 08:45:00.416697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f8a08dcfb3'
down_revision: Union[str, Sequence[str], None] = '3a2e34081573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('degree', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('degree_certificates_url', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('hospital_name', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('practice_location', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('consultation_mode', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('affiliation_letter_url', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('consultation_fee', sa.Float(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('available_days', sa.JSON(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('time_slots', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('emergency_availability', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('doctor_profiles', sa.Column('language', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('case_types', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('ai_assistance', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('doctor_profiles', sa.Column('terms_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('patient_profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('country', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('medical_summary_url', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('has_conditions', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('conditions', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('taking_meds', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('medications', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('allergy_reaction', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('past_surgeries', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('surgery_description', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('ongoing_treatments', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('smoking', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('alcohol', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('activity_level', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('sleep_duration', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('diet', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('language', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('patient_profiles', sa.Column('emergency_name', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_relation', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('emergency_phone', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('consent_storage', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('consent_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patient_profiles', sa.Column('consent_doctor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'consent_doctor')
    op.drop_column('patient_profiles', 'consent_ai')
    op.drop_column('patient_profiles', 'consent_storage')
    op.drop_column('patient_profiles', 'emergency_phone')
    op.drop_column('patient_profiles', 'emergency_relation')
    op.drop_column('patient_profiles', 'emergency_name')
    op.drop_column('patient_profiles', 'notifications')
    op.drop_column('patient_profiles', 'language')
    op.drop_column('patient_profiles', 'diet')
    op.drop_column('patient_profiles', 'sleep_duration')
    op.drop_column('patient_profiles', 'activity_level')
    op.drop_column('patient_profiles', 'alcohol')
    op.drop_column('patient_profiles', 'smoking')
    op.drop_column('patient_profiles', 'ongoing_treatments')
    op.drop_column('patient_profiles', 'surgery_description')
    op.drop_column('patient_profiles', 'past_surgeries')
    op.drop_column('patient_profiles', 'allergy_reaction')
    op.drop_column('patient_profiles', 'medications')
    op.drop_column('patient_profiles', 'taking_meds')
    op.drop_column('patient_profiles', 'conditions')
    op.drop_column('patient_profiles', 'has_conditions')
    op.drop_column('patient_profiles', 'medical_summary_url')
    op.drop_column('patient_profiles', 'occupation')
    op.drop_column('patient_profiles', 'country')
    op.drop_column('patient_profiles', 'city')
    op.drop_column('patient_profiles', 'weight')
    op.drop_column('patient_profiles', 'height')
    op.drop_column('doctor_profiles', 'terms_accepted')
    op.drop_column('doctor_profiles', 'ai_assistance')
    op.drop_column('doctor_profiles', 'case_types')
    op.drop_column('doctor_profiles', 'language')
    op.drop_column('doctor_profiles', 'emergency_availability')
    op.drop_column('doctor_profiles', 'time_slots')
    op.drop_column('doctor_profiles', 'available_days')
    op.drop_column('doctor_profiles', 'consultation_fee')
    op.drop_column('doctor_profiles', 'affiliation_letter_url')
    op.drop_column('doctor_profiles', 'consultation_mode')
    op.drop_column('doctor_profiles', 'practice_location')
    op.drop_column('doctor_profiles', 'hospital_name')
    op.drop_column('doctor_profiles', 'degree_certificates_url')
    op.drop_column('doctor_profiles', 'degree')
    op.drop_column('doctor_profiles', 'profile_photo_url')
    # ### end Alembic commands ###
