"""Add server_default to bmdc_verified

Revision ID: ef3e96945a9f
Revises: bffcf6a630a1
Create Date: 2026-01-07 00:22:03.024197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3e96945a9f'
down_revision: Union[str, Sequence[str], None] = 'bffcf6a630a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
