"""initial schema with profiles, patients, and doctors

Revision ID: f5419eaa3cf6
Revises: 
Create Date: 2025-12-22 06:56:38.235863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5419eaa3cf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profiles',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('bmdc_number', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('bmdc_document_url', sa.String(), nullable=True),
    sa.Column('bmdc_document_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('bmdc_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('verification_notes', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('bmdc_number')
    )
    op.create_table('patient_profiles',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('allergies', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DOCTOR', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='accountstatus'), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('patient_profiles')
    op.drop_table('doctor_profiles')
    # ### end Alembic commands ###
